( function () {
	"use strict";

	//	Publication 28
	//	C1 Street Suffix Abbreviations
	//	http://pe.usps.gov/text/pub28/28apc_002.htm
	//
	//	Tweaked a little

	var clean = require( "../../clean" );
	var logStatus = require( "../../logStatus");

	var streetType = {
		types: {
			"ALLEE": "ALY",
			"ALLEY": "ALY",
			"ALLY": "ALY",
			"ALLE": "ALY",
			"ALY": "ALY",
			"ANEX": "ANX",
			"ANNEX": "ANX",
			"ANNX": "ANX",
			"ANX": "ANX",
			"ARCADE": "ARC",
			"ARC": "ARC",
			"AV": "AVE",
			"AVEN": "AVE",
			"AVENU": "AVE",
			"AVENUE": "AVE",
			"AVN": "AVE",
			"AVNUE": "AVE",
			"AVE": "AVE",
			"BAYOO": "BYU",
			"BAYOU": "BYU",
			"BYU": "BYU",
			"BEACH": "BCH",
			"BCH": "BCH",
			"BEND": "BND",
			"BND": "BND",
			"BLUF": "BLF",
			"BLUFF": "BLF",
			"BLF": "BLF",
			"BLUFFS": "BLFS",
			"BLUFS": "BLFS",
			"BLFFS": "BLFS",
			"BLFS": "BLFS",
			"BOT": "BTM",
			"BOTM": "BTM",
			"BOTTM": "BTM",
			"BOTTOM": "BTM",
			"BTM": "BTM",
			"BOUL": "BLVD",
			"BOULEVARD": "BLVD",
			"BOULV": "BLVD",
			"BLVD": "BLVD",
			"BRNCH": "BR",
			"BRCH": "BR",
			"BRANCH": "BR",
			"BR": "BR",
			"BRDGE": "BRG",
			"BRIDGE": "BRG",
			"BRIDG": "BRG",
			"BRG": "BRG",
			"BROOK": "BRK",
			"BRK": "BRK",
			"BROOKS": "BRKS",
			"BRKS": "BRKS",
			"BURG": "BG",
			"BG": "BG",
			"BURGS": "BGS",
			"BGS": "BGS",
			"BYPA": "BYP",
			"BYPAS": "BYP",
			"BYPASS": "BYP",
			"BYPS": "BYP",
			"BYP": "BYP",
			"CAMP": "CP",
			"CMP": "CP",
			"CP": "CP",
			"CANYN": "CYN",
			"CANYON": "CYN",
			"CNYN": "CYN",
			"CYN": "CYN",
			"CAPE": "CPE",
			"CPE": "CPE",
			"CAUSEWAY": "CSWY",
			"CAUSWA": "CSWY",
			"CAUSWAY": "CSWY",
			"CSWY": "CSWY",
			"CEN": "CTR",
			"CENT": "CTR",
			"CENTER": "CTR",
			"CENTR": "CTR",
			"CENTRE": "CTR",
			"CNTER": "CTR",
			"CNTR": "CTR",
			"CTR": "CTR",
			"CENTERS": "CTRS",
			"CTRS": "CTRS",
			"CIRC": "CIR",
			"CIRCL": "CIR",
			"CIRCLE": "CIR",
			"CRCL": "CIR",
			"CRCLE": "CIR",
			"CIR": "CIR",
			"CIRCLES": "CIRS",
			"CIRS": "CIRS",
			"CLIFF": "CLF",
			"CLF": "CLF",
			"CLIFFS": "CLFS",
			"CLFS": "CLFS",
			"CLUB": "CLB",
			"CLB": "CLB",
			"COMMON": "CMN",
			"CMN": "CMN",
			"COMMONS": "CMNS",
			"CMNS": "CMNS",
			"CORNER": "COR",
			"COR": "COR",
			"CORNERS": "CORS",
			"CORS": "CORS",
			"COURSE": "CRSE",
			"CRSE": "CRSE",
			"COURT": "CT",
			"CRT": "CT",
			"CT": "CT",
			"COURTS": "CTS",
			"CRTS": "CTS",
			"CTS": "CTS",
			"COVE": "CV",
			"CV": "CV",
			"COVES": "CVS",
			"CVS": "CVS",
			"CREEK": "CRK",
			"CRK": "CRK",
			"CK": "CRK",
			"CR": "CRK",
			"CRESCENT": "CRES",
			"CRESENT": "CRES",
			"CRECENT": "CRES",
			"CRSENT": "CRES",
			"CRSNT": "CRES",
			"CRSCNT": "CRES",
			"CRES": "CRES",
			"CREST": "CRST",
			"CRST": "CRST",
			"CROSSING": "XING",
			"CRSSNG": "XING",
			"CRSNG": "XING",
			"CRSSING": "XING",
			"XING": "XING",
			"CROSSROAD": "XRD",
			"XRD": "XRD",
			"CROSSROADS": "XRDS",
			"XRDS": "XRDS",
			"CURVE": "CURV",
			"CURV": "CURV",
			"DALE": "DL",
			"DL": "DL",
			"DAM": "DM",
			"DM": "DM",
			"DIV": "DV",
			"DIVIDE": "DV",
			"DVD": "DV",
			"DV": "DV",
			"DRIV": "DR",
			"DRIVE": "DR",
			"DRV": "DR",
			"DR": "DR",
			"DRIVES": "DRS",
			"DRS": "DRS",
			"ESTATE": "EST",
			"EST": "EST",
			"ESTATES": "ESTS",
			"ESTS": "ESTS",
			"EXP": "EXPY",
			"EXPR": "EXPY",
			"EXPRESS": "EXPY",
			"EXPRESSWAY": "EXPY",
			"EXPW": "EXPY",
			"EXPY": "EXPY",
			"EXTENSION": "EXT",
			"EXTN": "EXT",
			"EXTNSN": "EXT",
			"EXT": "EXT",
			"EXTENSIONS": "EXTS",
			"EXTS": "EXTS",
			"FLL": "FALL",
			"FALL": "FALL",
			"FALLS": "FLS",
			"FLS": "FLS",
			"FERRY": "FRY",
			"FRRY": "FRY",
			"FRY": "FRY",
			"FIELD": "FLD",
			"FLD": "FLD",
			"FIELDS": "FLDS",
			"FLDS": "FLDS",
			"FLAT": "FLT",
			"FLT": "FLT",
			"FLATS": "FLTS",
			"FLTS": "FLTS",
			"FORD": "FRD",
			"FRD": "FRD",
			"FORDS": "FRDS",
			"FRDS": "FRDS",
			"FOREST": "FRST",
			"FORESTS": "FRST",
			"FRST": "FRST",
			"FORG": "FRG",
			"FORGE": "FRG",
			"FRG": "FRG",
			"FORGES": "FRGS",
			"FRGS": "FRGS",
			"FORK": "FRK",
			"FRK": "FRK",
			"FORKS": "FRKS",
			"FRKS": "FRKS",
			"FORT": "FT",
			"FRT": "FT",
			"FT": "FT",
			"FREEWAY": "FWY",
			"FREEWY": "FWY",
			"FRWAY": "FWY",
			"FRWY": "FWY",
			"FWY": "FWY",
			"GARDEN": "GDN",
			"GARDN": "GDN",
			"GRDEN": "GDN",
			"GRDN": "GDN",
			"GDN": "GDN",
			"GARDENS": "GDNS",
			"GRDNS": "GDNS",
			"GDNS": "GDNS",
			"GATEWAY": "GTWY",
			"GATEWY": "GTWY",
			"GATWAY": "GTWY",
			"GTWAY": "GTWY",
			"GTWY": "GTWY",
			"GLEN": "GLN",
			"GLN": "GLN",
			"GLENS": "GLNS",
			"GLNS": "GLNS",
			"GREEN": "GRN",
			"GRN": "GRN",
			"GREENS": "GRNS",
			"GRNS": "GRNS",
			"GROV": "GRV",
			"GROVE": "GRV",
			"GRV": "GRV",
			"GROVES": "GRVS",
			"GRVS": "GRVS",
			"HARB": "HBR",
			"HARBOR": "HBR",
			"HARBR": "HBR",
			"HRBOR": "HBR",
			"HBR": "HBR",
			"HARBORS": "HBRS",
			"HBRS": "HBRS",
			"HAVEN": "HVN",
			"HAVN": "HVN",
			"HVN": "HVN",
			"HT": "HTS",
			"HEIGHT": "HTS",
			"HEIGHTS": "HTS",
			"HGTS": "HTS",
			"HTS": "HTS",
			"HIGHWAY": "HWY",
			"HIGHWY": "HWY",
			"HIWAY": "HWY",
			"HIWY": "HWY",
			"HWAY": "HWY",
			"HWY": "HWY",
			"HILL": "HL",
			"HL": "HL",
			"HILLS": "HLS",
			"HLS": "HLS",
			"HLLW": "HOLW",
			"HOLLOW": "HOLW",
			"HOLLOWS": "HOLW",
			"HOLWS": "HOLW",
			"HOLW": "HOLW",
			"INLET": "INLT",
			"INLT": "INLT",
			"ISLAND": "IS",
			"ISLND": "IS",
			"IS": "IS",
			"ISLANDS": "ISS",
			"ISLNDS": "ISS",
			"ISS": "ISS",
			"ISLES": "ISLE",
			"ISLE": "ISLE",
			"JCTION": "JCT",
			"JCTN": "JCT",
			"JUNCTION": "JCT",
			"JUNCTN": "JCT",
			"JUNCTON": "JCT",
			"JCT": "JCT",
			"JCTNS": "JCTS",
			"JUNCTIONS": "JCTS",
			"JCTS": "JCTS",
			"KEY": "KY",
			"KY": "KY",
			"KEYS": "KYS",
			"KYS": "KYS",
			"KNOL": "KNL",
			"KNOLL": "KNL",
			"KNL": "KNL",
			"KNOLLS": "KNLS",
			"KNLS": "KNLS",
			"LAKE": "LK",
			"LK": "LK",
			"LAKES": "LKS",
			"LKS": "LKS",
			"LAND": "LAND",
			"LANDING": "LNDG",
			"LNDNG": "LNDG",
			"LNDG": "LNDG",
			"LANE": "LN",
			"LANES": "LN",
			"LA": "LN",
			"LN": "LN",
			"LIGHT": "LGT",
			"LGT": "LGT",
			"LIGHTS": "LGTS",
			"LGTS": "LGTS",
			"LOAF": "LF",
			"LF": "LF",
			"LOCK": "LCK",
			"LCK": "LCK",
			"LOCKS": "LCKS",
			"LCKS": "LCKS",
			"LDGE": "LDG",
			"LODG": "LDG",
			"LODGE": "LDG",
			"LDG": "LDG",
			"LP": "LOOP",
			"LOOP": "LOOP",
			"LOOPS": "LOOP",
			"MALL": "MALL",
			"MANOR": "MNR",
			"MNR": "MNR",
			"MANORS": "MNRS",
			"MNRS": "MNRS",
			"MEADOW": "MDW",
			"MDW": "MDW",
			"MEADOWS": "MDWS",
			"MEDOWS": "MDWS",
			"MDWS": "MDWS",
			"MEWS": "MEWS",
			"MILL": "ML",
			"ML": "ML",
			"MILLS": "MLS",
			"MLS": "MLS",
			"MISSION": "MSN",
			"MISSN": "MSN",
			"MSSN": "MSN",
			"MSN": "MSN",
			"MOTORWAY": "MTWY",
			"MOTORWY": "MTWY",
			"MTRWY": "MTWY",
			"MTWY": "MTWY",
			"MNT": "MT",
			"MOUNT": "MT",
			"MT": "MT",
			"MNTAIN": "MTN",
			"MNTN": "MTN",
			"MOUNTAIN": "MTN",
			"MOUNTIN": "MTN",
			"MTIN": "MTN",
			"MTN": "MTN",
			"MOUNTAINS": "MTNS",
			"MNTNS": "MTNS",
			"MTNS": "MTNS",
			"NECK": "NCK",
			"NCK": "NCK",
			"ORCHARD": "ORCH",
			"ORCHRD": "ORCH",
			"ORCH": "ORCH",
			"OVL": "OVAL",
			"OVAL": "OVAL",
			"OVERPASS": "OPAS",
			"OPAS": "OPAS",
			"PARK": "PARK",
			"PK": "PARK",
			"PARKS": "PARK",
			"PRKS": "PARK",
			"PRK": "PARK",
			"PARKWAY": "PKWY",
			"PARKWY": "PKWY",
			"PKWAY": "PKWY",
			"PKY": "PKWY",
			"PARKWAYS": "PKWY",
			"PARKWYS": "PKWY",
			"PKWAYS": "PKWY",
			"PKYS": "PKWY",
			"PKWYS": "PKWY",
			"PKWY": "PKWY",
			"PASS": "PASS",
			"PASSAGE": "PSGE",
			"PSGE": "PSGE",
			"PATHS": "PATH",
			"PATH": "PATH",
			"PIKES": "PIKE",
			"PIKE": "PIKE",
			"PINE": "PNE",
			"PNE": "PNE",
			"PINES": "PNES",
			"PNES": "PNES",
			"PLACE": "PL",
			"PL": "PL",
			"PLAIN": "PLN",
			"PLN": "PLN",
			"PLAINS": "PLNS",
			"PLAINES": "PLNS",
			"PLNS": "PLNS",
			"PLAZA": "PLZ",
			"PLZA": "PLZ",
			"PLZ": "PLZ",
			"POINT": "PT",
			"PT": "PT",
			"POINTS": "PTS",
			"PTS": "PTS",
			"PORT": "PRT",
			"PRT": "PRT",
			"PORTS": "PRTS",
			"PRTS": "PRTS",
			"PRAIRIE": "PR",
			"PRARIE": "PR",
			"PRR": "PR",
			"PR": "PR",
			"RAD": "RADL",
			"RADIAL": "RADL",
			"RADIEL": "RADL",
			"RADL": "RADL",
			"RAMP": "RAMP",
			"RANCH": "RNCH",
			"RANCHES": "RNCH",
			"RNCHS": "RNCH",
			"RNCH": "RNCH",
			"RAPID": "RPD",
			"RPD": "RPD",
			"RAPIDS": "RPDS",
			"RPDS": "RPDS",
			"REST": "RST",
			"RST": "RST",
			"RDGE": "RDG",
			"RIDGE": "RDG",
			"RDG": "RDG",
			"RIDGES": "RDGS",
			"RDGS": "RDGS",
			"RIVER": "RIV",
			"RVR": "RIV",
			"RIVR": "RIV",
			"RIV": "RIV",
			"ROAD": "RD",
			"RD": "RD",
			"ROADS": "RDS",
			"RDS": "RDS",
			"ROUTE": "RTE",
			"RTE": "RTE",
			"ROW": "ROW",
			"RUE": "RUE",
			"RUN": "RUN",
			"SHOAL": "SHL",
			"SHL": "SHL",
			"SHOALS": "SHLS",
			"SHLS": "SHLS",
			"SHOAR": "SHR",
			"SHORE": "SHR",
			"SHR": "SHR",
			"SHORES": "SHRS",
			"SHOARS": "SHRS",
			"SHRS": "SHRS",
			"SKYWAY": "SKWY",
			"SKYWY": "SKWY",
			"SKWY": "SKWY",
			"SPNG": "SPG",
			"SPRING": "SPG",
			"SPRNG": "SPG",
			"SPG": "SPG",
			"SPNGS": "SPGS",
			"SPRINGS": "SPGS",
			"SPRNGS": "SPGS",
			"SPGS": "SPGS",
			"SPR": "SPUR",
			"SPRS": "SPUR",
			"SPURS": "SPUR",
			"SPUR": "SPUR",
			"SQR": "SQ",
			"SQRE": "SQ",
			"SQU": "SQ",
			"SQUARE": "SQ",
			"SQ": "SQ",
			"SQRS": "SQS",
			"SQUARES": "SQS",
			"SQS": "SQS",
			"STATION": "STA",
			"STATN": "STA",
			"STN": "STA",
			"STA": "STA",
			"STRAV": "STRA",
			"STRAVEN": "STRA",
			"STRAVENUE": "STRA",
			"STRAVN": "STRA",
			"STRVN": "STRA",
			"STRVNUE": "STRA",
			"STRAVE": "STRA",
			"STRA": "STRA",
			"STREAM": "STRM",
			"STREME": "STRM",
			"STRM": "STRM",
			"STREET": "ST",
			"STRT": "ST",
			"STR": "ST",
			"ST": "ST",
			"STREETS": "STS",
			"STS": "STS",
			"SUMIT": "SMT",
			"SUMITT": "SMT",
			"SUMMIT": "SMT",
			"SMT": "SMT",
			"TERR": "TER",
			"TERRACE": "TER",
			"TER": "TER",
			"THROUGHWAY": "TRWY",
			"TRWY": "TRWY",
			"TRACE": "TRCE",
			"TRACES": "TRCE",
			"TRCE": "TRCE",
			"TRACK": "TRAK",
			"TRACKS": "TRAK",
			"TRK": "TRAK",
			"TRKS": "TRAK",
			"TRAK": "TRAK",
			"TRAFFICWAY": "TRFY",
			"TRFY": "TRFY",
			"TRAIL": "TRL",
			"TR": "TRL",
			"TRAILS": "TRL",
			"TRLS": "TRL",
			"TRL": "TRL",
			"TRAILER": "TRLR",
			"TRAILERS": "TRLR",
			"TRLRS": "TRLR",
			"TRLR": "TRLR",
			"TUNEL": "TUNL",
			"TUNLS": "TUNL",
			"TUNNEL": "TUNL",
			"TUNNELS": "TUNL",
			"TUNNL": "TUNL",
			"TUNL": "TUNL",
			"TRNPK": "TPKE",
			"TURNPIKE": "TPKE",
			"TURNPK": "TPKE",
			"TPK": "TPKE",
			"TRPK": "TPKE",
			"TPKE": "TPKE",
			"UNDERPASS": "UPAS",
			"UNDRPASS": "UPAS",
			"UNDRPSS": "UPAS",
			"UDRPSS": "UPAS",
			"UDRPS": "UPAS",
			"UPASS": "UPAS",
			"UPAS": "UPAS",
			"UNION": "UN",
			"UN": "UN",
			"UNIONS": "UNS",
			"UNS": "UNS",
			"VALLEY": "VLY",
			"VALLY": "VLY",
			"VLLY": "VLY",
			"VLY": "VLY",
			"VALLEYS": "VLYS",
			"VLYS": "VLYS",
			"VDCT": "VIA",
			"VIADCT": "VIA",
			"VIADUCT": "VIA",
			"VIA": "VIA",
			"VIEW": "VW",
			"VW": "VW",
			"VIEWS": "VWS",
			"VWS": "VWS",
			"VILL": "VLG",
			"VILG": "VLG",
			"VILLAG": "VLG",
			"VILLAGE": "VLG",
			"VILLG": "VLG",
			"VILLIAGE": "VLG",
			"VLG": "VLG",
			"VILLAGES": "VLGS",
			"VILLS": "VLGS",
			"VLGS": "VLGS",
			"VILLE": "VL",
			"VL": "VL",
			"VIST": "VIS",
			"VISTA": "VIS",
			"VST": "VIS",
			"VSTA": "VIS",
			"VIS": "VIS",
			"WALKS": "WALK",
			"WALK": "WALK",
			"WLL": "WALL",
			"WALL": "WALL",
			"WAY": "WAY",
			"WY": "WAY",
			"WAYS": "WAYS",
			"WELL": "WL",
			"WEL": "WL",
			"WL": "WL",
			"WELLS": "WLS",
			"WELS": "WLS",
			"WLS": "WLS"
		},
		match: function ( type ) {
			var cleanType;

			if ( !type ) {
				return;
			}
			cleanType = clean( type );
			if ( !cleanType ) {
				return;
			}
			cleanType = cleanType.toUpperCase();

			if ( this.types.hasOwnProperty( cleanType ) ) {
				return this.types[ cleanType ];
			}

			return;
		},
		parse: function ( typeString ) {
			var typeParts;
			var type;
			var cleanType;

			logStatus( "parse" );

			if ( !typeString ) {
				return;
			}
			cleanType = clean( typeString );
			if ( !cleanType ) {
				return;
			}
			cleanType = cleanType.toUpperCase();

			logStatus( "parse", "cleanType", cleanType );

			if ( this.typeRegExp.test( cleanType ) ) {

				logStatus( "parse", "typeString", typeString );

				typeParts = cleanType.match( this.typeRegExp );

				logStatus( "parse", "typeParts", typeParts );

				if ( typeParts[ 1 ] !== undefined ) {
					type = this.match( typeParts[ 1 ] );
				}
			}
			else {
				logStatus( "parse", null, "test failed" );
			}

			return type;
		}
	};

	var type;
	var types = "";

	for ( type in streetType.types ) {
		if ( streetType.types.hasOwnProperty( type ) ) {
			types += types ? "|" + type : type;
		}
	}

	streetType.typeRegExp = new RegExp( "^\\s*(" + types + ")\\s*$", "i" );
	streetType.typePartialRegExp = new RegExp( types, "i" );

	module.exports = streetType;

} ).call( this );