( function () {
	"use strict";

	//	Publication 28
	//	C1 Street Suffix Abbreviations
	//	http://pe.usps.gov/text/pub28/28apc_002.htm
	//
	//	Tweaked a little

	var clean = require( "../../clean" );
	var logStatus = require( "../../logStatus");

	var streetType = {
		types: {
			"ALLEE": "ALY",
			"ALLEY": "ALY",
			"ALLY": "ALY",
			"ALLE": "ALY",
			"ALY": "ALY",
			"ANEX": "ANX",
			"ANNEX": "ANX",
			"ANNX": "ANX",
			"ANX": "ANX",
			"ARCADE": "ARC",
			"ARC": "ARC",
			"AV": "AVE",
			"AVEN": "AVE",
			"AVENU": "AVE",
			"AVENUE": "AVE",
			"AVN": "AVE",
			"AVNUE": "AVE",
			"AVE": "AVE",
			"BAYOO": "BYU",
			"BAYOU": "BYU",
			"BYU": "BYU",
			"BEACH": "BCH",
			"BCH": "BCH",
			"BEND": "BND",
			"BND": "BND",
			"BLUF": "BLF",
			"BLUFF": "BLF",
			"BLF": "BLF",
			"BLUFFS": "BLFS",
			"BLUFS": "BLFS",
			"BLFFS": "BLFS",
			"BLFS": "BLFS",
			"BOT": "BTM",
			"BOTM": "BTM",
			"BOTTM": "BTM",
			"BOTTOM": "BTM",
			"BTM": "BTM",
			"BOUL": "BLVD",
			"BOULEVARD": "BLVD",
			"BOULV": "BLVD",
			"BLVD": "BLVD",
			"BRNCH": "BR",
			"BRCH": "BR",
			"BRANCH": "BR",
			"BR": "BR",
			"BRDGE": "BRG",
			"BRIDGE": "BRG",
			"BRIDG": "BRG",
			"BRG": "BRG",
			"BROOK": "BRK",
			"BRK": "BRK",
			"BROOKS": "BRKS",
			"BRKS": "BRKS",
			"BURG": "BG",
			"BG": "BG",
			"BURGS": "BGS",
			"BGS": "BGS",
			"BYPA": "BYP",
			"BYPAS": "BYP",
			"BYPASS": "BYP",
			"BYPS": "BYP",
			"BYP": "BYP",
			"CAMP": "CP",
			"CMP": "CP",
			"CP": "CP",
			"CANYN": "CYN",
			"CANYON": "CYN",
			"CNYN": "CYN",
			"CYN": "CYN",
			"CAPE": "CPE",
			"CPE": "CPE",
			"CAUSEWAY": "CSWY",
			"CAUSWA": "CSWY",
			"CAUSWAY": "CSWY",
			"CSWY": "CSWY",
			"CEN": "CTR",
			"CENT": "CTR",
			"CENTER": "CTR",
			"CENTR": "CTR",
			"CENTRE": "CTR",
			"CNTER": "CTR",
			"CNTR": "CTR",
			"CTR": "CTR",
			"CENTERS": "CTRS",
			"CTRS": "CTRS",
			"CIRC": "CIR",
			"CIRCL": "CIR",
			"CIRCLE": "CIR",
			"CRCL": "CIR",
			"CRCLE": "CIR",
			"CIR": "CIR",
			"CIRCLES": "CIRS",
			"CIRS": "CIRS",
			"CLIFF": "CLF",
			"CLF": "CLF",
			"CLIFFS": "CLFS",
			"CLFS": "CLFS",
			"CLUB": "CLB",
			"CLB": "CLB",
			"COMMON": "CMN",
			"CMN": "CMN",
			"COMMONS": "CMNS",
			"CMNS": "CMNS",
			"CORNER": "COR",
			"COR": "COR",
			"CORNERS": "CORS",
			"CORS": "CORS",
			"COURSE": "CRSE",
			"CRSE": "CRSE",
			"COURT": "CT",
			"CRT": "CT",
			"CT": "CT",
			"COURTS": "CTS",
			"CRTS": "CTS",
			"CTS": "CTS",
			"COVE": "CV",
			"CV": "CV",
			"COVES": "CVS",
			"CVS": "CVS",
			"CREEK": "CRK",
			"CRK": "CRK",
			"CK": "CRK",
			"CR": "CRK",
			"CRESCENT": "CRES",
			"CRESENT": "CRES",
			"CRECENT": "CRES",
			"CRSENT": "CRES",
			"CRSNT": "CRES",
			"CRSCNT": "CRES",
			"CRES": "CRES",
			"CREST": "CRST",
			"CRST": "CRST",
			"CROSSING": "XING",
			"CRSSNG": "XING",
			"CRSNG": "XING",
			"CRSSING": "XING",
			"XING": "XING",
			"CROSSROAD": "XRD",
			"XRD": "XRD",
			"CROSSROADS": "XRDS",
			"XRDS": "XRDS",
			"CURVE": "CURV",
			"CURV": "CURV",
			"DALE": "DL",
			"DL": "DL",
			"DAM": "DM",
			"DM": "DM",
			"DIV": "DV",
			"DIVIDE": "DV",
			"DVD": "DV",
			"DV": "DV",
			"DRIV": "DR",
			"DRIVE": "DR",
			"DRV": "DR",
			"DR": "DR",
			"DRIVES": "DRS",
			"DRS": "DRS",
			"ESTATE": "EST",
			"EST": "EST",
			"ESTATES": "ESTS",
			"ESTS": "ESTS",
			"EXP": "EXPY",
			"EXPR": "EXPY",
			"EXPRESS": "EXPY",
			"EXPRESSWAY": "EXPY",
			"EXPW": "EXPY",
			"EXPY": "EXPY",
			"EXTENSION": "EXT",
			"EXTN": "EXT",
			"EXTNSN": "EXT",
			"EXT": "EXT",
			"EXTENSIONS": "EXTS",
			"EXTS": "EXTS",
			"FLL": "FALL",
			"FALL": "FALL",
			"FALLS": "FLS",
			"FLS": "FLS",
			"FERRY": "FRY",
			"FRRY": "FRY",
			"FRY": "FRY",
			"FIELD": "FLD",
			"FLD": "FLD",
			"FIELDS": "FLDS",
			"FLDS": "FLDS",
			"FLAT": "FLT",
			"FLT": "FLT",
			"FLATS": "FLTS",
			"FLTS": "FLTS",
			"FORD": "FRD",
			"FRD": "FRD",
			"FORDS": "FRDS",
			"FRDS": "FRDS",
			"FOREST": "FRST",
			"FORESTS": "FRST",
			"FRST": "FRST",
			"FORG": "FRG",
			"FORGE": "FRG",
			"FRG": "FRG",
			"FORGES": "FRGS",
			"FRGS": "FRGS",
			"FORK": "FRK",
			"FRK": "FRK",
			"FORKS": "FRKS",
			"FRKS": "FRKS",
			"FORT": "FT",
			"FRT": "FT",
			"FT": "FT",
			"FREEWAY": "FWY",
			"FREEWY": "FWY",
			"FRWAY": "FWY",
			"FRWY": "FWY",
			"FWY": "FWY",
			"GARDEN": "GDN",
			"GARDN": "GDN",
			"GRDEN": "GDN",
			"GRDN": "GDN",
			"GDN": "GDN",
			"GARDENS": "GDNS",
			"GRDNS": "GDNS",
			"GDNS": "GDNS",
			"GATEWAY": "GTWY",
			"GATEWY": "GTWY",
			"GATWAY": "GTWY",
			"GTWAY": "GTWY",
			"GTWY": "GTWY",
			"GLEN": "GLN",
			"GLN": "GLN",
			"GLENS": "GLNS",
			"GLNS": "GLNS",
			"GREEN": "GRN",
			"GRN": "GRN",
			"GREENS": "GRNS",
			"GRNS": "GRNS",
			"GROV": "GRV",
			"GROVE": "GRV",
			"GRV": "GRV",
			"GROVES": "GRVS",
			"GRVS": "GRVS",
			"HARB": "HBR",
			"HARBOR": "HBR",
			"HARBR": "HBR",
			"HRBOR": "HBR",
			"HBR": "HBR",
			"HARBORS": "HBRS",
			"HBRS": "HBRS",
			"HAVEN": "HVN",
			"HAVN": "HVN",
			"HVN": "HVN",
			"HT": "HTS",
			"HEIGHT": "HTS",
			"HEIGHTS": "HTS",
			"HGTS": "HTS",
			"HTS": "HTS",
			"HIGHWAY": "HWY",
			"HIGHWY": "HWY",
			"HIWAY": "HWY",
			"HIWY": "HWY",
			"HWAY": "HWY",
			"HWY": "HWY",
			"HILL": "HL",
			"HL": "HL",
			"HILLS": "HLS",
			"HLS": "HLS",
			"HLLW": "HOLW",
			"HOLLOW": "HOLW",
			"HOLLOWS": "HOLW",
			"HOLWS": "HOLW",
			"HOLW": "HOLW",
			"INLET": "INLT",
			"INLT": "INLT",
			"ISLAND": "IS",
			"ISLND": "IS",
			"IS": "IS",
			"ISLANDS": "ISS",
			"ISLNDS": "ISS",
			"ISS": "ISS",
			"ISLES": "ISLE",
			"ISLE": "ISLE",
			"JCTION": "JCT",
			"JCTN": "JCT",
			"JUNCTION": "JCT",
			"JUNCTN": "JCT",
			"JUNCTON": "JCT",
			"JCT": "JCT",
			"JCTNS": "JCTS",
			"JUNCTIONS": "JCTS",
			"JCTS": "JCTS",
			"KEY": "KY",
			"KY": "KY",
			"KEYS": "KYS",
			"KYS": "KYS",
			"KNOL": "KNL",
			"KNOLL": "KNL",
			"KNL": "KNL",
			"KNOLLS": "KNLS",
			"KNLS": "KNLS",
			"LAKE": "LK",
			"LK": "LK",
			"LAKES": "LKS",
			"LKS": "LKS",
			"LAND": "LAND",
			"LANDING": "LNDG",
			"LNDNG": "LNDG",
			"LNDG": "LNDG",
			"LANE": "LN",
			"LANES": "LN",
			"LA": "LN",
			"LN": "LN",
			"LIGHT": "LGT",
			"LGT": "LGT",
			"LIGHTS": "LGTS",
			"LGTS": "LGTS",
			"LOAF": "LF",
			"LF": "LF",
			"LOCK": "LCK",
			"LCK": "LCK",
			"LOCKS": "LCKS",
			"LCKS": "LCKS",
			"LDGE": "LDG",
			"LODG": "LDG",
			"LODGE": "LDG",
			"LDG": "LDG",
			"LP": "LOOP",
			"LOOP": "LOOP",
			"LOOPS": "LOOP",
			"MALL": "MALL",
			"MANOR": "MNR",
			"MNR": "MNR",
			"MANORS": "MNRS",
			"MNRS": "MNRS",
			"MEADOW": "MDW",
			"MDW": "MDW",
			"MEADOWS": "MDWS",
			"MEDOWS": "MDWS",
			"MDWS": "MDWS",
			"MEWS": "MEWS",
			"MILL": "ML",
			"ML": "ML",
			"MILLS": "MLS",
			"MLS": "MLS",
			"MISSION": "MSN",
			"MISSN": "MSN",
			"MSSN": "MSN",
			"MSN": "MSN",
			"MOTORWAY": "MTWY",
			"MOTORWY": "MTWY",
			"MTRWY": "MTWY",
			"MTWY": "MTWY",
			"MNT": "MT",
			"MOUNT": "MT",
			"MT": "MT",
			"MNTAIN": "MTN",
			"MNTN": "MTN",
			"MOUNTAIN": "MTN",
			"MOUNTIN": "MTN",
			"MTIN": "MTN",
			"MTN": "MTN",
			"MOUNTAINS": "MTNS",
			"MNTNS": "MTNS",
			"MTNS": "MTNS",
			"NECK": "NCK",
			"NCK": "NCK",
			"ORCHARD": "ORCH",
			"ORCHRD": "ORCH",
			"ORCH": "ORCH",
			"OVL": "OVAL",
			"OVAL": "OVAL",
			"OVERPASS": "OPAS",
			"OPAS": "OPAS",
			"PARK": "PARK",
			"PK": "PARK",
			"PARKS": "PARK",
			"PRKS": "PARK",
			"PRK": "PARK",
			"PARKWAY": "PKWY",
			"PARKWY": "PKWY",
			"PKWAY": "PKWY",
			"PKY": "PKWY",
			"PARKWAYS": "PKWY",
			"PARKWYS": "PKWY",
			"PKWAYS": "PKWY",
			"PKYS": "PKWY",
			"PKWYS": "PKWY",
			"PKWY": "PKWY",
			"PASS": "PASS",
			"PASSAGE": "PSGE",
			"PSGE": "PSGE",
			"PATHS": "PATH",
			"PATH": "PATH",
			"PIKES": "PIKE",
			"PIKE": "PIKE",
			"PINE": "PNE",
			"PNE": "PNE",
			"PINES": "PNES",
			"PNES": "PNES",
			"PLACE": "PL",
			"PL": "PL",
			"PLAIN": "PLN",
			"PLN": "PLN",
			"PLAINS": "PLNS",
			"PLAINES": "PLNS",
			"PLNS": "PLNS",
			"PLAZA": "PLZ",
			"PLZA": "PLZ",
			"PLZ": "PLZ",
			"POINT": "PT",
			"PT": "PT",
			"POINTS": "PTS",
			"PTS": "PTS",
			"PORT": "PRT",
			"PRT": "PRT",
			"PORTS": "PRTS",
			"PRTS": "PRTS",
			"PRAIRIE": "PR",
			"PRARIE": "PR",
			"PRR": "PR",
			"PR": "PR",
			"RAD": "RADL",
			"RADIAL": "RADL",
			"RADIEL": "RADL",
			"RADL": "RADL",
			"RAMP": "RAMP",
			"RANCH": "RNCH",
			"RANCHES": "RNCH",
			"RNCHS": "RNCH",
			"RNCH": "RNCH",
			"RAPID": "RPD",
			"RPD": "RPD",
			"RAPIDS": "RPDS",
			"RPDS": "RPDS",
			"REST": "RST",
			"RST": "RST",
			"RDGE": "RDG",
			"RIDGE": "RDG",
			"RDG": "RDG",
			"RIDGES": "RDGS",
			"RDGS": "RDGS",
			"RIVER": "RIV",
			"RVR": "RIV",
			"RIVR": "RIV",
			"RIV": "RIV",
			"ROAD": "RD",
			"RD": "RD",
			"ROADS": "RDS",
			"RDS": "RDS",
			"ROUTE": "RTE",
			"RTE": "RTE",
			"ROW": "ROW",
			"RUE": "RUE",
			"RUN": "RUN",
			"SHOAL": "SHL",
			"SHL": "SHL",
			"SHOALS": "SHLS",
			"SHLS": "SHLS",
			"SHOAR": "SHR",
			"SHORE": "SHR",
			"SHR": "SHR",
			"SHORES": "SHRS",
			"SHOARS": "SHRS",
			"SHRS": "SHRS",
			"SKYWAY": "SKWY",
			"SKYWY": "SKWY",
			"SKWY": "SKWY",
			"SPNG": "SPG",
			"SPRING": "SPG",
			"SPRNG": "SPG",
			"SPG": "SPG",
			"SPNGS": "SPGS",
			"SPRINGS": "SPGS",
			"SPRNGS": "SPGS",
			"SPGS": "SPGS",
			"SPR": "SPUR",
			"SPRS": "SPUR",
			"SPURS": "SPUR",
			"SPUR": "SPUR",
			"SQR": "SQ",
			"SQRE": "SQ",
			"SQU": "SQ",
			"SQUARE": "SQ",
			"SQ": "SQ",
			"SQRS": "SQS",
			"SQUARES": "SQS",
			"SQS": "SQS",
			"STATION": "STA",
			"STATN": "STA",
			"STN": "STA",
			"STA": "STA",
			"STRAV": "STRA",
			"STRAVEN": "STRA",
			"STRAVENUE": "STRA",
			"STRAVN": "STRA",
			"STRVN": "STRA",
			"STRVNUE": "STRA",
			"STRAVE": "STRA",
			"STRA": "STRA",
			"STREAM": "STRM",
			"STREME": "STRM",
			"STRM": "STRM",
			"STREET": "ST",
			"STRT": "ST",
			"STR": "ST",
			"ST": "ST",
			"STREETS": "STS",
			"STS": "STS",
			"SUMIT": "SMT",
			"SUMITT": "SMT",
			"SUMMIT": "SMT",
			"SMT": "SMT",
			"TERR": "TER",
			"TERRACE": "TER",
			"TER": "TER",
			"THROUGHWAY": "TRWY",
			"TRWY": "TRWY",
			"TRACE": "TRCE",
			"TRACES": "TRCE",
			"TRCE": "TRCE",
			"TRACK": "TRAK",
			"TRACKS": "TRAK",
			"TRK": "TRAK",
			"TRKS": "TRAK",
			"TRAK": "TRAK",
			"TRAFFICWAY": "TRFY",
			"TRFY": "TRFY",
			"TRAIL": "TRL",
			"TR": "TRL",
			"TRAILS": "TRL",
			"TRLS": "TRL",
			"TRL": "TRL",
			"TRAILER": "TRLR",
			"TRAILERS": "TRLR",
			"TRLRS": "TRLR",
			"TRLR": "TRLR",
			"TUNEL": "TUNL",
			"TUNLS": "TUNL",
			"TUNNEL": "TUNL",
			"TUNNELS": "TUNL",
			"TUNNL": "TUNL",
			"TUNL": "TUNL",
			"TRNPK": "TPKE",
			"TURNPIKE": "TPKE",
			"TURNPK": "TPKE",
			"TPK": "TPKE",
			"TRPK": "TPKE",
			"TPKE": "TPKE",
			"UNDERPASS": "UPAS",
			"UNDRPASS": "UPAS",
			"UNDRPSS": "UPAS",
			"UDRPSS": "UPAS",
			"UDRPS": "UPAS",
			"UPASS": "UPAS",
			"UPAS": "UPAS",
			"UNION": "UN",
			"UN": "UN",
			"UNIONS": "UNS",
			"UNS": "UNS",
			"VALLEY": "VLY",
			"VALLY": "VLY",
			"VLLY": "VLY",
			"VLY": "VLY",
			"VALLEYS": "VLYS",
			"VLYS": "VLYS",
			"VDCT": "VIA",
			"VIADCT": "VIA",
			"VIADUCT": "VIA",
			"VIA": "VIA",
			"VIEW": "VW",
			"VW": "VW",
			"VIEWS": "VWS",
			"VWS": "VWS",
			"VILL": "VLG",
			"VILG": "VLG",
			"VILLAG": "VLG",
			"VILLAGE": "VLG",
			"VILLG": "VLG",
			"VILLIAGE": "VLG",
			"VLG": "VLG",
			"VILLAGES": "VLGS",
			"VILLS": "VLGS",
			"VLGS": "VLGS",
			"VILLE": "VL",
			"VL": "VL",
			"VIST": "VIS",
			"VISTA": "VIS",
			"VST": "VIS",
			"VSTA": "VIS",
			"VIS": "VIS",
			"WALKS": "WALK",
			"WALK": "WALK",
			"WLL": "WALL",
			"WALL": "WALL",
			"WAY": "WAY",
			"WY": "WAY",
			"WAYS": "WAYS",
			"WELL": "WL",
			"WEL": "WL",
			"WL": "WL",
			"WELLS": "WLS",
			"WELS": "WLS",
			"WLS": "WLS"
		},
		match: function ( type ) {
			var cleanType;

			if ( !type ) {
				return;
			}
			cleanType = clean( type );
			if ( !cleanType ) {
				return;
			}
			cleanType = cleanType.toUpperCase();

			if ( this.types.hasOwnProperty( cleanType ) ) {
				return this.types[ cleanType ];
			}

			if ( this.multiple.types.hasOwnProperty( cleanType ) ) {
				return this.multiple.types[ cleanType ];
			}

			return;
		},
		parse: function ( typeString ) {
			var typeParts;
			var type;
			var cleanType;

			logStatus( "parse" );

			if ( !typeString ) {
				return;
			}
			cleanType = clean( typeString );
			if ( !cleanType ) {
				return;
			}
			cleanType = cleanType.toUpperCase();

			logStatus( "parse", "cleanType", cleanType );

			if ( this.typeRegExp.test( cleanType ) ) {

				logStatus( "parse", "typeString", typeString );

				typeParts = cleanType.match( this.typeRegExp );

				logStatus( "parse", "typeParts", typeParts );

				if ( typeParts[ 1 ] !== undefined ) {
					type = this.match( typeParts[ 1 ] );
				}
			}
			else {
				logStatus( "parse", null, "test failed" );
			}

			return type;
		},
		multiple: {
			types: {
				"ALLEES": "ALY",
				"ALLEYS": "ALY",
				"ALLYS": "ALY",
				"ALLES": "ALY",
				"ALYS": "ALY",
				"ANEXES": "ANX",
				"ANEXS": "ANX",
				"ANNEXS": "ANX",
				"ANNXS": "ANX",
				"ANXS": "ANX",
				"ARCADES": "ARC",
				"ARCS": "ARC",
				"AVS": "AVE",
				"AVENS": "AVE",
				"AVENUS": "AVE",
				"AVENUES": "AVE",
				"AVNS": "AVE",
				"AVNUES": "AVE",
				"AVES": "AVE",
				"BAYOOS": "BYU",
				"BAYOUS": "BYU",
				"BYUS": "BYU",
				"BEACHES": "BCH",
				"BEACHS": "BCH",
				"BCHS": "BCH",
				"BENDS": "BND",
				"BNDS": "BND",
				"BLUFS": "BLF",
				"BLUFFS": "BLF",
				"BLFS": "BLF",
				"BLFFS": "BLF",
				"BOTS": "BTM",
				"BOTMS": "BTM",
				"BOTTMS": "BTM",
				"BOTTOMS": "BTM",
				"BTMS": "BTM",
				"BOULS": "BLVD",
				"BOULEVARDS": "BLVD",
				"BOULVS": "BLVD",
				"BLVDS": "BLVD",
				"BRNCHS": "BR",
				"BRCHS": "BR",
				"BRANCHS": "BR",
				"BRANCHES": "BR",
				"BRS": "BR",
				"BRDGES": "BRG",
				"BRIDGES": "BRG",
				"BRIDGS": "BRG",
				"BRGS": "BRG",
				"BROOKS": "BRK",
				"BRKS": "BRK",
				"BURGS": "BG",
				"BGS": "BG",
				"BYPAS": "BYP",
				"BYPASS": "BYP",
				"BYPSS": "BYP",
				"BYPS": "BYP",
				"CAMPS": "CP",
				"CMPS": "CP",
				"CPS": "CP",
				"CANYNS": "CYN",
				"CANYONS": "CYN",
				"CNYNS": "CYN",
				"CYNS": "CYN",
				"CAPES": "CPE",
				"CPES": "CPE",
				"CAUSEWAYS": "CSWY",
				"CAUSWAS": "CSWY",
				"CAUSWAYS": "CSWY",
				"CSWYS": "CSWY",
				"CENS": "CTR",
				"CENTS": "CTR",
				"CENTERS": "CTR",
				"CENTRS": "CTR",
				"CENTRES": "CTR",
				"CNTERS": "CTR",
				"CNTRS": "CTR",
				"CTRS": "CTR",
				"CIRCS": "CIR",
				"CIRCLS": "CIR",
				"CIRCLES": "CIR",
				"CRCLS": "CIR",
				"CRCLES": "CIR",
				"CIRS": "CIR",
				"CLIFFS": "CLF",
				"CLFS": "CLF",
				"CLUBS": "CLB",
				"CLBS": "CLB",
				"COMMONS": "CMN",
				"CMNS": "CMN",
				"CORNERS": "COR",
				"CORS": "COR",
				"COURSES": "CRSE",
				"CRSES": "CRSE",
				"COURTS": "CT",
				"CRTS": "CT",
				"CTS": "CT",
				"COURTSS": "CTS",
				"CRTSS": "CTS",
				"CTSS": "CTS",
				"COVES": "CV",
				"CVS": "CV",
				"COVESS": "CVS",
				"CVSS": "CVS",
				"CREEKS": "CRK",
				"CRKS": "CRK",
				"CKS": "CRK",
				"CRS": "CRK",
				"CRESCENTS": "CRES",
				"CRESENTS": "CRES",
				"CRECENTS": "CRES",
				"CRSENTS": "CRES",
				"CRSNTS": "CRES",
				"CRSCNTS": "CRES",
				"CRESS": "CRES",
				"CRESTS": "CRST",
				"CRSTS": "CRST",
				"CROSSINGS": "XING",
				"CRSSNGS": "XING",
				"CRSNGS": "XING",
				"CRSSINGS": "XING",
				"XINGS": "XING",
				"CROSSROADS": "XRD",
				"XRDS": "XRD",
				"CROSSROADSS": "XRDS",
				"XRDSS": "XRDS",
				"CURVES": "CURV",
				"CURVS": "CURV",
				"DALES": "DL",
				"DLS": "DL",
				"DAMS": "DM",
				"DMS": "DM",
				"DIVS": "DV",
				"DIVIDES": "DV",
				"DVDS": "DV",
				"DVS": "DV",
				"DRIVS": "DR",
				"DRIVES": "DR",
				"DRVS": "DR",
				"DRS": "DR",
				"DRIVESS": "DRS",
				"DRSS": "DRS",
				"ESTATES": "EST",
				"ESTS": "EST",
				"ESTATESS": "ESTS",
				"ESTSS": "ESTS",
				"EXPS": "EXPY",
				"EXPRS": "EXPY",
				"EXPRESSS": "EXPY",
				"EXPRESSWAYS": "EXPY",
				"EXPWS": "EXPY",
				"EXPYS": "EXPY",
				"EXTENSIONS": "EXT",
				"EXTNS": "EXT",
				"EXTNSNS": "EXT",
				"EXTS": "EXT",
				"EXTENSIONSS": "EXTS",
				"EXTSS": "EXTS",
				"FLLS": "FALL",
				"FALLS": "FALL",
				"FALLSS": "FLS",
				"FLSS": "FLS",
				"FERRYS": "FRY",
				"FRRYS": "FRY",
				"FRYS": "FRY",
				"FIELDS": "FLD",
				"FLDS": "FLD",
				"FIELDSS": "FLDS",
				"FLDSS": "FLDS",
				"FLATS": "FLT",
				"FLTS": "FLT",
				"FLATSS": "FLTS",
				"FLTSS": "FLTS",
				"FORDS": "FRD",
				"FRDS": "FRD",
				"FORDSS": "FRDS",
				"FRDSS": "FRDS",
				"FORESTS": "FRST",
				"FORESTSS": "FRST",
				"FRSTS": "FRST",
				"FORGS": "FRG",
				"FORGES": "FRG",
				"FRGS": "FRG",
				"FORGESS": "FRGS",
				"FRGSS": "FRGS",
				"FORKS": "FRK",
				"FRKS": "FRK",
				"FORKSS": "FRKS",
				"FRKSS": "FRKS",
				"FORTS": "FT",
				"FRTS": "FT",
				"FTS": "FT",
				"FREEWAYS": "FWY",
				"FREEWYS": "FWY",
				"FRWAYS": "FWY",
				"FRWYS": "FWY",
				"FWYS": "FWY",
				"GARDENS": "GDN",
				"GARDNS": "GDN",
				"GRDENS": "GDN",
				"GRDNS": "GDN",
				"GDNS": "GDN",
				"GARDENSS": "GDNS",
				"GRDNSS": "GDNS",
				"GDNSS": "GDNS",
				"GATEWAYS": "GTWY",
				"GATEWYS": "GTWY",
				"GATWAYS": "GTWY",
				"GTWAYS": "GTWY",
				"GTWYS": "GTWY",
				"GLENS": "GLN",
				"GLNS": "GLN",
				"GLENSS": "GLNS",
				"GLNSS": "GLNS",
				"GREENS": "GRN",
				"GRNS": "GRN",
				"GREENSS": "GRNS",
				"GRNSS": "GRNS",
				"GROVS": "GRV",
				"GROVES": "GRV",
				"GRVS": "GRV",
				"GROVESS": "GRVS",
				"GRVSS": "GRVS",
				"HARBS": "HBR",
				"HARBORS": "HBR",
				"HARBRS": "HBR",
				"HRBORS": "HBR",
				"HBRS": "HBR",
				"HARBORSS": "HBRS",
				"HBRSS": "HBRS",
				"HAVENS": "HVN",
				"HAVNS": "HVN",
				"HVNS": "HVN",
				"HTS": "HTS",
				"HEIGHTS": "HTS",
				"HEIGHTSS": "HTS",
				"HGTSS": "HTS",
				"HTSS": "HTS",
				"HIGHWAYS": "HWY",
				"HIGHWYS": "HWY",
				"HIWAYS": "HWY",
				"HIWYS": "HWY",
				"HWAYS": "HWY",
				"HWYS": "HWY",
				"HILLS": "HL",
				"HLS": "HL",
				"HILLSS": "HLS",
				"HLSS": "HLS",
				"HLLWS": "HOLW",
				"HOLLOWS": "HOLW",
				"HOLLOWSS": "HOLW",
				"HOLWSS": "HOLW",
				"HOLWS": "HOLW",
				"INLETS": "INLT",
				"INLTS": "INLT",
				"ISLANDS": "IS",
				"ISLNDS": "IS",
				"ISS": "IS",
				"ISLANDSS": "ISS",
				"ISLNDSS": "ISS",
				"ISSS": "ISS",
				"ISLESS": "ISLE",
				"ISLES": "ISLE",
				"JCTIONS": "JCT",
				"JCTNS": "JCT",
				"JUNCTIONS": "JCT",
				"JUNCTNS": "JCT",
				"JUNCTONS": "JCT",
				"JCTS": "JCT",
				"JCTNSS": "JCTS",
				"JUNCTIONSS": "JCTS",
				"JCTSS": "JCTS",
				"KEYS": "KY",
				"KYS": "KY",
				"KEYSS": "KYS",
				"KYSS": "KYS",
				"KNOLS": "KNL",
				"KNOLLS": "KNL",
				"KNLS": "KNL",
				"KNOLLSS": "KNLS",
				"KNLSS": "KNLS",
				"LAKES": "LK",
				"LKS": "LK",
				"LAKESS": "LKS",
				"LKSS": "LKS",
				"LANDS": "LAND",
				"LANDINGS": "LNDG",
				"LNDNGS": "LNDG",
				"LNDGS": "LNDG",
				"LANES": "LN",
				"LANESS": "LN",
				"LAS": "LN",
				"LNS": "LN",
				"LIGHTS": "LGT",
				"LGTS": "LGT",
				"LIGHTSS": "LGTS",
				"LGTSS": "LGTS",
				"LOAFS": "LF",
				"LFS": "LF",
				"LOCKS": "LCK",
				"LCKS": "LCK",
				"LOCKSS": "LCKS",
				"LCKSS": "LCKS",
				"LDGES": "LDG",
				"LODGS": "LDG",
				"LODGES": "LDG",
				"LDGS": "LDG",
				"LPS": "LOOP",
				"LOOPS": "LOOP",
				"LOOPSS": "LOOP",
				"MALLS": "MALL",
				"MANORS": "MNR",
				"MNRS": "MNR",
				"MANORSS": "MNRS",
				"MNRSS": "MNRS",
				"MEADOWS": "MDW",
				"MDWS": "MDW",
				"MEADOWSS": "MDWS",
				"MEDOWSS": "MDWS",
				"MDWSS": "MDWS",
				"MEWSS": "MEWS",
				"MILLS": "ML",
				"MLS": "ML",
				"MILLSS": "MLS",
				"MLSS": "MLS",
				"MISSIONS": "MSN",
				"MISSNS": "MSN",
				"MSSNS": "MSN",
				"MSNS": "MSN",
				"MOTORWAYS": "MTWY",
				"MOTORWYS": "MTWY",
				"MTRWYS": "MTWY",
				"MTWYS": "MTWY",
				"MNTS": "MT",
				"MOUNTS": "MT",
				"MTS": "MT",
				"MNTAINS": "MTN",
				"MNTNS": "MTN",
				"MOUNTAINS": "MTN",
				"MOUNTINS": "MTN",
				"MTINS": "MTN",
				"MTNS": "MTN",
				"MOUNTAINSS": "MTNS",
				"MNTNSS": "MTNS",
				"MTNSS": "MTNS",
				"NECKS": "NCK",
				"NCKS": "NCK",
				"ORCHARDS": "ORCH",
				"ORCHRDS": "ORCH",
				"ORCHS": "ORCH",
				"OVLS": "OVAL",
				"OVALS": "OVAL",
				"OVERPASSS": "OPAS",
				"OPASS": "OPAS",
				"PARKS": "PARK",
				"PKS": "PARK",
				"PARKSS": "PARK",
				"PRKSS": "PARK",
				"PRKS": "PARK",
				"PARKWAYS": "PKWY",
				"PARKWYS": "PKWY",
				"PKWAYS": "PKWY",
				"PKYS": "PKWY",
				"PARKWAYSS": "PKWY",
				"PARKWYSS": "PKWY",
				"PKWAYSS": "PKWY",
				"PKYSS": "PKWY",
				"PKWYSS": "PKWY",
				"PKWYS": "PKWY",
				"PASSS": "PASS",
				"PASSAGES": "PSGE",
				"PSGES": "PSGE",
				"PATHSS": "PATH",
				"PATHS": "PATH",
				"PIKESS": "PIKE",
				"PIKES": "PIKE",
				"PINES": "PNE",
				"PNES": "PNE",
				"PINESS": "PNES",
				"PNESS": "PNES",
				"PLACES": "PL",
				"PLS": "PL",
				"PLAINS": "PLN",
				"PLNS": "PLN",
				"PLAINSS": "PLNS",
				"PLAINESS": "PLNS",
				"PLNSS": "PLNS",
				"PLAZAS": "PLZ",
				"PLZAS": "PLZ",
				"PLZS": "PLZ",
				"POINTS": "PT",
				"PTS": "PT",
				"POINTSS": "PTS",
				"PTSS": "PTS",
				"PORTS": "PRT",
				"PRTS": "PRT",
				"PORTSS": "PRTS",
				"PRTSS": "PRTS",
				"PRAIRIES": "PR",
				"PRARIES": "PR",
				"PRRS": "PR",
				"PRS": "PR",
				"RADS": "RADL",
				"RADIALS": "RADL",
				"RADIELS": "RADL",
				"RADLS": "RADL",
				"RAMPS": "RAMP",
				"RANCHS": "RNCH",
				"RANCHESS": "RNCH",
				"RNCHSS": "RNCH",
				"RNCHS": "RNCH",
				"RAPIDS": "RPD",
				"RPDS": "RPD",
				"RAPIDSS": "RPDS",
				"RPDSS": "RPDS",
				"RESTS": "RST",
				"RSTS": "RST",
				"RDGES": "RDG",
				"RIDGES": "RDG",
				"RDGS": "RDG",
				"RIDGESS": "RDGS",
				"RDGSS": "RDGS",
				"RIVERS": "RIV",
				"RVRS": "RIV",
				"RIVRS": "RIV",
				"RIVS": "RIV",
				"ROADS": "RD",
				"RDS": "RD",
				"ROADSS": "RDS",
				"RDSS": "RDS",
				"ROUTES": "RTE",
				"RTES": "RTE",
				"ROWS": "ROW",
				"RUES": "RUE",
				"RUNS": "RUN",
				"SHOALS": "SHL",
				"SHLS": "SHL",
				"SHOALSS": "SHLS",
				"SHLSS": "SHLS",
				"SHOARS": "SHR",
				"SHORES": "SHR",
				"SHRS": "SHR",
				"SHORESS": "SHRS",
				"SHOARSS": "SHRS",
				"SHRSS": "SHRS",
				"SKYWAYS": "SKWY",
				"SKYWYS": "SKWY",
				"SKWYS": "SKWY",
				"SPNGS": "SPG",
				"SPRINGS": "SPG",
				"SPRNGS": "SPG",
				"SPGS": "SPG",
				"SPNGSS": "SPGS",
				"SPRINGSS": "SPGS",
				"SPRNGSS": "SPGS",
				"SPGSS": "SPGS",
				"SPRS": "SPUR",
				"SPRSS": "SPUR",
				"SPURSS": "SPUR",
				"SPURS": "SPUR",
				"SQRS": "SQ",
				"SQRES": "SQ",
				"SQUS": "SQ",
				"SQUARES": "SQ",
				"SQS": "SQ",
				"SQRSS": "SQS",
				"SQUARESS": "SQS",
				"SQSS": "SQS",
				"STATIONS": "STA",
				"STATNS": "STA",
				"STNS": "STA",
				"STAS": "STA",
				"STRAVS": "STRA",
				"STRAVENS": "STRA",
				"STRAVENUES": "STRA",
				"STRAVNS": "STRA",
				"STRVNS": "STRA",
				"STRVNUES": "STRA",
				"STRAVES": "STRA",
				"STRAS": "STRA",
				"STREAMS": "STRM",
				"STREMES": "STRM",
				"STRMS": "STRM",
				"STREETS": "ST",
				"STRTS": "ST",
				"STRS": "ST",
				"STS": "ST",
				"STREETSS": "STS",
				"STSS": "STS",
				"SUMITS": "SMT",
				"SUMITTS": "SMT",
				"SUMMITS": "SMT",
				"SMTS": "SMT",
				"TERRS": "TER",
				"TERRACES": "TER",
				"TERS": "TER",
				"THROUGHWAYS": "TRWY",
				"TRWYS": "TRWY",
				"TRACES": "TRCE",
				"TRACESS": "TRCE",
				"TRCES": "TRCE",
				"TRACKS": "TRAK",
				"TRACKSS": "TRAK",
				"TRKS": "TRAK",
				"TRKSS": "TRAK",
				"TRAKS": "TRAK",
				"TRAFFICWAYS": "TRFY",
				"TRFYS": "TRFY",
				"TRAILS": "TRL",
				"TRS": "TRL",
				"TRAILSS": "TRL",
				"TRLSS": "TRL",
				"TRLS": "TRL",
				"TRAILERS": "TRLR",
				"TRAILERSS": "TRLR",
				"TRLRSS": "TRLR",
				"TRLRS": "TRLR",
				"TUNELS": "TUNL",
				"TUNLSS": "TUNL",
				"TUNNELS": "TUNL",
				"TUNNELSS": "TUNL",
				"TUNNLS": "TUNL",
				"TUNLS": "TUNL",
				"TRNPKS": "TPKE",
				"TURNPIKES": "TPKE",
				"TURNPKS": "TPKE",
				"TPKS": "TPKE",
				"TRPKS": "TPKE",
				"TPKES": "TPKE",
				"UNDERPASSS": "UPAS",
				"UNDRPASSS": "UPAS",
				"UNDRPSSS": "UPAS",
				"UDRPSSS": "UPAS",
				"UDRPSS": "UPAS",
				"UPASSS": "UPAS",
				"UPASS": "UPAS",
				"UNIONS": "UN",
				"UNS": "UN",
				"UNIONSS": "UNS",
				"UNSS": "UNS",
				"VALLEYS": "VLY",
				"VALLYS": "VLY",
				"VLLYS": "VLY",
				"VLYS": "VLY",
				"VALLEYSS": "VLYS",
				"VLYSS": "VLYS",
				"VDCTS": "VIA",
				"VIADCTS": "VIA",
				"VIADUCTS": "VIA",
				"VIAS": "VIA",
				"VIEWS": "VW",
				"VWS": "VW",
				"VIEWSS": "VWS",
				"VWSS": "VWS",
				"VILLS": "VLG",
				"VILGS": "VLG",
				"VILLAGS": "VLG",
				"VILLAGES": "VLG",
				"VILLGS": "VLG",
				"VILLIAGES": "VLG",
				"VLGS": "VLG",
				"VILLAGESS": "VLGS",
				"VILLSS": "VLGS",
				"VLGSS": "VLGS",
				"VILLES": "VL",
				"VLS": "VL",
				"VISTS": "VIS",
				"VISTAS": "VIS",
				"VSTS": "VIS",
				"VSTAS": "VIS",
				"VISS": "VIS",
				"WALKSS": "WALK",
				"WALKS": "WALK",
				"WLLS": "WALL",
				"WALLS": "WALL",
				"WAYS": "WAY",
				"WYS": "WAY",
				"WAYSS": "WAYS",
				"WELLS": "WL",
				"WELS": "WL",
				"WLS": "WL",
				"WELLSS": "WLS",
				"WELSS": "WLS",
				"WLSS": "WLS"
			},
			match: function ( plural ) {
				var cleanPlural;

				if ( !plural ) {
					return;
				}
				cleanPlural = clean( plural );
				if ( !cleanPlural ) {
					return;
				}
				cleanPlural = cleanPlural.toUpperCase();

				if ( this.types.hasOwnProperty( cleanPlural ) ) {
					return this.types[ cleanPlural ];
				}

				return;
			},
			parse: function ( multipleString ) {
				var typeParts;
				var type;
				var cleanMultiple;

				logStatus( "parse" );

				if ( !multipleString ) {
					return;
				}
				cleanMultiple = clean( multipleString );
				if ( !cleanMultiple ) {
					return;
				}
				cleanMultiple = cleanMultiple.toUpperCase();

				logStatus( "parse", "cleanMultiple", cleanMultiple );

				if ( this.multipleRegExp.test( cleanMultiple ) ) {

					logStatus( "parse", "multipleString", multipleString );

					typeParts = cleanMultiple.match( this.multipleRegExp );

					logStatus( "parse", "typeParts", typeParts );

					if ( typeParts[ 1 ] !== undefined ) {
						type = this.match( typeParts[ 1 ] );
					}
				}
				else {
					logStatus( "parse", null, "test failed" );
				}

				return type;
			}
		}
	};

	var type;
	var types = "";
	var multiple;
	var multiples = "";

	for ( type in streetType.types ) {
		if ( streetType.types.hasOwnProperty( type ) ) {
			types += types ? "|" + type : type;
		}
	}

	for ( multiple in streetType.multiples ) {
		if ( streetType.multiple.types.hasOwnProperty( multiple ) ) {
			multiples += multiples ? "|" + multiple : multiple;
		}
	}

	streetType.typeRegExp = new RegExp( "^\\s*(" + types + ")\\s*$", "i" );
	streetType.typePartialRegExp = new RegExp( types, "i" );

	streetType.multiple.typeRegExp = new RegExp( "^\\s*(" + multiples + ")\\s*$", "i" );
	streetType.multiple.typePartialRegExp = new RegExp( multiples, "i" );

	module.exports = streetType;

} ).call( this );